spring:
  application:
    name: naughts-and-crosses-api
  security.oauth2.resourceserver.jwt.issuer-uri: ${auth.issuer.url:}
  main:
    banner-mode: OFF
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver}

management:
  endpoints:
    web.exposure.include: health,info
  endpoint:
    health:
      probes.enabled: true
      show-details: always