spring:
  application:
    name: naughts-and-crosses-api
  security.oauth2.resourceserver.jwt:
    public-key-location: ${auth.issuer.public.key:}
    issuer-uri: ${auth.issuer.url:}
  main:
    banner-mode: OFF
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver}

management:
  endpoints:
    web:
      exposure.include: health,info
      cors:
        allowed-origins: ${cors.allowed.origins}
        allowed-methods: GET
        allowed-headers: '*'
  endpoint:
    health:
      probes.enabled: true
      show-details: always

logging.level.org.springframework.security: DEBUG