spring:
  application:
    name: naughts-and-crosses-api
  security.oauth2.resourceserver.jwt.issuer-uri: ${auth.issuer.url:}
  main:
    banner-mode: OFF
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver}