version: '3.9'

services:
  naughts-and-crosses-api:
    image: naughts-and-crosses-api
    container_name: naughts-and-crosses-api
    profiles: [ "docker-api" ]
    ports:
      - 3002:80
    environment:
      CORS_ALLOWED_ORIGINS: 3001
      DATABASE_URL: jdbc:postgresql://naughts-and-crosses-db:5432/naughts-and-crosses-api
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DRIVER: org.postgresql.Driver
      BROKER_SSL_ENABLED: false
      BROKER_HOST: activemq
      BROKER_PORT: 61613
      BROKER_CLIENT_LOGIN: artemis
      BROKER_CLIENT_PASSCODE: artemis
      BROKER_SYSTEM_LOGIN: artemis
      BROKER_SYSTEM_PASSCODE: artemis
      AUTH_ISSUER_URL: "http://cognito:9229/%POOL_ID%"
      AWS_COGNITO_LOCAL_DOCKER: true
      AWS_COGNITO_USER_POOL_ID: "%POOL_ID%"
      AWS_COGNITO_REGION_NAME: eu-central-1
      AWS_COGNITO_ENDPOINT_OVERRIDE: http://cognito:9229
      AWS_COGNITO_ACCESS_KEY_ID: abc
      AWS_COGNITO_SECRET_ACCESS_KEY: 123
    restart: on-failure
    depends_on:
      - naughts-and-crosses-db
      - activemq
      - cognito

  naughts-and-crosses-db:
    image: postgres:16-alpine
    container_name: naughts-and-crosses-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naughts-and-crosses-api

  cognito:
    image: michaelruocco/cognito-local:latest
    container_name: cognito
    ports:
      - 9229:9229
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - ISSUER_HOST=cognito
      - CODE=9999

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - 61613:61613
      - 8161:8161