version: '3.9'

services:
  naughts-and-crosses-api:
    image: naughts-and-crosses-api
    container_name: naughts-and-crosses-api
    profiles: [ "docker-api" ]
    ports:
      - 3002:80
    environment:
      CORS_ALLOWED_ORIGINS: 3001
      DATABASE_URL: jdbc:postgresql://naughts-and-crosses-db:5432/naughts-and-crosses-api
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DRIVER: org.postgresql.Driver
      BROKER_HOST: activemq
      BROKER_PORT: 61613
      BROKER_CLIENT_LOGIN: artemis
      BROKER_CLIENT_PASSCODE: artemis
      BROKER_SYSTEM_LOGIN: artemis
      BROKER_SYSTEM_PASSCODE: artemis
      AUTH_ISSUER_URL: http://keycloak:4021/realms/naughts-and-crosses-local
      KEYCLOAK_ADMIN_CLIENT_ID: naughts-and-crosses-api
      KEYCLOAK_ADMIN_CLIENT_SECRET: naughts-and-crosses-api-secret
    restart: on-failure
    depends_on:
      - naughts-and-crosses-db
      - activemq
      - keycloak

  naughts-and-crosses-db:
    image: postgres:16-alpine
    container_name: naughts-and-crosses-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naughts-and-crosses-api

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: [ "start-dev", "--http-port=4021", "--import-realm" ]
    ports:
      - 4021:4021
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./app/spring/src/testFixtures/resources/keycloak:/opt/keycloak/data/import
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://keycloak:4021/realms/naughts-and-crosses-local/.well-known/openid-configuration" ]
      interval: 10s
      timeout: 10s
      retries: 15

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - 61613:61613
      - 8161:8161