version: '3.9'

services:
  naughts-and-crosses-api:
    image: naughts-and-crosses-api
    container_name: naughts-and-crosses-api
    profiles: [ "docker-api" ]
    ports:
      - 3002:80
    environment:
      CORS_ALLOWED_ORIGINS: 3001
      DATABASE_URL: jdbc:postgresql://naughts-and-crosses-db:5432/naughts-and-crosses-api
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DRIVER: org.postgresql.Driver
    restart: on-failure
    depends_on:
      - naughts-and-crosses-db

  naughts-and-crosses-db:
    image: postgres:16-alpine
    container_name: naughts-and-crosses-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naughts-and-crosses-api