services:
  naughts-and-crosses-api:
    image: naughts-and-crosses-api
    container_name: naughts-and-crosses-api
    profiles: [ "docker-api" ]
    ports:
      - 3002:80
    environment:
      CORS_ALLOWED_ORIGINS: 3001
      DATABASE_URL: jdbc:postgresql://naughts-and-crosses-db:5432/naughts-and-crosses-api
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DRIVER: org.postgresql.Driver
      BROKER_SSL_ENABLED: false
      BROKER_HOST: activemq
      BROKER_PORT: 61613
      BROKER_CLIENT_LOGIN: artemis
      BROKER_CLIENT_PASSCODE: artemis
      BROKER_SYSTEM_LOGIN: artemis
      BROKER_SYSTEM_PASSCODE: artemis
      AUTH_ISSUER_URL: "http://cognito:9229/local_4RsGXSAf"
      AWS_COGNITO_USER_POOL_ID: "local_4RsGXSAf"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "6b0j5hb1u25z290vv502lfl1c"
      AWS_COGNITO_REGION_NAME: eu-central-1
      AWS_COGNITO_ENDPOINT_OVERRIDE: http://cognito:9229
      AWS_COGNITO_ACCESS_KEY_ID: abc
      AWS_COGNITO_SECRET_ACCESS_KEY: 123
      CLAM_AV_HOST: antivirus
      CLAM_AV_PORT: 3310
      CLAM_AV_CONNECT_TIMEOUT: 2
      CLAM_AV_READ_TIMEOUT: 20
    restart: on-failure
    depends_on:
      - naughts-and-crosses-db
      - activemq
      - cognito
      - antivirus

  naughts-and-crosses-db:
    image: postgres:16-alpine
    container_name: naughts-and-crosses-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naughts-and-crosses-api

  cognito:
    image: michaelruocco/cognito-local:latest
    container_name: cognito
    volumes:
      - ./app/spring/src/testFixtures/resources/cognito:/app/.cognito/db/
    ports:
      - 9229:9229
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - ISSUER_HOST=cognito
      - CODE=9999

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - 61613:61613
      - 8161:8161

  antivirus:
    image: clamav/clamav-debian
    container_name: antivirus
    ports:
      - 3310:3310