version: '3.9'

services:
  naughts-and-crosses-db:
    image: postgres:16-alpine
    container_name: naughts-and-crosses-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naughts-and-crosses-api